- name: install tom
  hosts: tomcat
  become: yes
  tasks:
    - name: check if the playbook is being executed on supported os
      ansible.builtin.fail:
        msg: "This playbook is designed to work on ubuntu only"
      when: ansible_facts['distribution'] != "Ubuntu"
    - name: install java
      ansible.builtin.apt:
        name: "{{ java_package }}"
        state: present
        update_cache:  yes